version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: serviciosdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

  backend:
    image: node:18
    container_name: node_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - db

  php:
    image: php:8.2-apache
    container_name: php_service
    volumes:
      - ./frondend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
